AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'minimal-app/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - 'on'
    - 'fn'
    - 'cb'

Lint/StructNewOverride:
  Enabled: false
