# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'rack', '~> 3.0'
gem 'rackup', '~> 2.0'
gem 'dotenv', '~> 3.1'

gem 'mobiscroll-connect', path: '..'
