using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;

namespace Mobiscroll.Connect.Tests.TestHelpers;

/// <summary>One case from <c>Fixtures/webhook-vectors.json</c>, generated by the Connect server's signer.</summary>
internal sealed record WebhookVector(
    string Name,
    string Body,
    Dictionary<string, string> Headers,
    string[] PublicKeys,
    long Now,
    bool Valid);

internal static class WebhookVectors
{
    private static readonly Lazy<JsonElement> Root = new(() =>
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "webhook-vectors.json");
        using var document = JsonDocument.Parse(File.ReadAllBytes(path));
        return document.RootElement.Clone();
    });

    public static IReadOnlyList<WebhookVector> Cases => Root.Value.GetProperty("cases")
        .EnumerateArray()
        .Select(c => new WebhookVector(
            c.GetProperty("name").GetString()!,
            c.GetProperty("body").GetString()!,
            c.GetProperty("headers").EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetString()!),
            c.GetProperty("publicKeys").EnumerateArray().Select(k => k.GetString()!).ToArray(),
            c.GetProperty("now").GetInt64(),
            c.GetProperty("valid").GetBoolean()))
        .ToList();

    public static string Key(string name) => Root.Value.GetProperty("keys").GetProperty(name).GetString()!;

    public static WebhookVector ByName(string name) => Cases.Single(c => c.Name == name);
}
